# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "VideoEmbed"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  platform: youtube
  videoId:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  videoId:
    comment: 'You can find this in the URL of the video you want to embed. For example, https://www.youtube.com/watch?v=YOUR_VIDEO_ID, or for vimeo https://vimeo.com/YOUR_VIDEO_ID'
  platform:
    comment: 'Youtube or Vimeo'
    type: choice
    options:
      allow_empty: false
      value_key: id
      values:
        - id: youtube
          name: Youtube
        - id: vimeo
          name: Vimeo