# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Text Break Review"
  description: A result image review where the text breaks out of the image frame
  icon: reviews
  tags: [review, connected]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    usePersonImage: false
    reviews:
      - review:
  styles:
    color_group: primary


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  review:
    type: select
    options:
      values: data.reviews
      value_key: id
      text_key: name