[functions]
  node_bundler = "esbuild"
[build]
  publish = "dist"
  command = "npm run eleventy"
[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  # Optional (but highly recommended). Defaults to [".cache"].
  paths = [".cache","dist/assets/images"]