# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Side By Side Service"
  description: A versatile section that combines text, images, and and a animation transitions between them.
  icon: ballot
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:generic/heading!
    services:
      - service:
  styles:
    color_group: primary
    imagePosition: left
    imageVisualInterest: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content:
    services:
      type: array
      comment: A list of services to display
