# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Country Input"
  description: ountry selector input
  icon: public
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  required: false
  helperText:
  

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  helper_text:
    comment: Helpful text for the user such as 'Your primary country of residence'
  id:
    instance_value: UUID
    hidden: true
