# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Blog Cards - 3 Posts"
  description: Shows up to 3 blog cards. Either the most recent or random
  icon:
  tags: [connected]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  contents:
    sectionId:
    showNote: true
    heading: bookshop:structure:headingBlocks
    randomize: false
  styles:
    color_group: primary
    cardStyle: default

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  cardStyle:
    type: select
    options:
      allow_empty: false
      value_key: id
      values:
        - name: Default
          id: default