# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Colored Call To Action"
  description: A visually loud call to action sure to get attention
  icon: exclamation
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    CallToAction: bookshop:generic/heading!
  styles:
    color_group: primary
    card_color_group: primary
    colorFromGroup: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  card_color_group:
    comment: "Select the color group of the call to action card"
  colorFromGroup:
    comment: "This determines the background color of the call to action card based on the card color group options"

