# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Form Overlapping Image"
  description: A form that overlaps an image of your choosing
  icon:
  tags: [form]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    image: bookshop:generic/image
    form: bookshop:simple/formBuilder!
  styles:
    color_group: primary
    form_color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
