# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Left Right Hero"
  description: A straight forward left right hero
  icon: feed
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:generic/heading!
    image: bookshop:generic/image!
  styles:
    color_group: primary
    headingRight: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  headingRight:
    type: switch
    comment: Weather the heading should be on the right
