# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Simple Hero"
  description:
  icon: feed
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  sectionId:
  heading: bookshop:generic/heading!

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
