# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Action Bar"
  description: "A persistent call to action at the bottom of a page"
  icon: bottom_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    buttons: [bookshop:structure:buttons]
  styles:
    color_group: primary
    colorFromGroup: background

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
