# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Simple Form Section"
  description: A simple form section with a heading
  icon:
  tags: [form]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    form: bookshop:simple/formBuilder!
  styles:
    color_group: primary
    

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
