# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Full Screen Image Hero"
  description: Provide concise information at the top of the page to engage website visitors
  icon: feed
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    highlightEybrow: false
    sectionId:
    eyebrow:
    headline:
    description: "Hello World!"
    buttons: [bookshop:structure:buttons]
    image: bookshop:structure:imgvid
  styles:
    color_group: primary
    contentAlignment: left
    textAlignment: left
    backgroundOpacity: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  styles:
    contentAlignment: left
    color_group: primary
  content:
    highlightEybrow: true
    eyebrow: eybrow
    headline: headline
    button:
      url: "#"
      text: "Button text"
      color_group: primary
    description: "Hello World!"
    image:
      _bookshop_name: generic/image
      imagePath: /images/tree.jpg
      imageAlt: Tree in the middle of a field with the sunsetting on the left

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image:
    label: Media
  contentAlignment:
    type: choice
    options:
      allow_empty: false
      value_key: id
      values:
        - name: Left
          id: left
          icon: format_align_left
        - name: Center
          id: center
          icon: format_align_center
        - name: Right
          id: right
          icon: format_align_right
  textAlignment:
    type: choice
    options:
      allow_empty: false
      value_key: id
      values:
        - name: Left
          id: left
          icon: format_align_left
        - name: Center
          id: center
          icon: format_align_center
        - name: Right
          id: right
          icon: format_align_right
  backgroundOpacity:
    type: range
    options:
      min: 0
      max: 100
      step: 5
      default: 50
    comment: Set the opacity percentage of the background
