# Metadata about this component, to be used in the CMS
spec:
  structures:
    - assets
    - card_imagery_blocks
    - resource
    - media
    - imgvid
  label: "Image"
  description: An image that wil be optimized
  icon: image
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  imagePath:
  imageAlt:
  yAxisPosition:
  imageSizes:
  class:
  imageNumber:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  imagePath: /images/tree.jpg
  imageAlt: Tree in the middle of a field with the sunsetting on the left
  imageSizes: 100vw

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  imageSizes:
    hidden: true  
  class:
    hidden: true
  imageNumber:
    hidden: true
  imageAlt:
    comment: "A concise text description of the image that will be used for accessibility. This not being filled out will hurt SEO."
  yAxisPosition:
    type: range
    options:
      min: 0
      max: 100
      step: 5
      default: 50
    comment: "This shifts the focus of the image up or down by percentage 1-100. 0 is the top of the image and 50 is the center of the image"

