# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Simple media Gallery"
  description: A simple media gallery
  icon: space_dashboard
  tags: []
  tabbed: true

# Make it so that the image set isn't an array of images but is just a single array.
# Recreate it correctly and ymlify it back into the grid component
# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    images: [bookshop:structure:media]
    buttons: [bookshop:structure:buttons]
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
