# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Select Input"
  description: A select input with custom options
  icon: checklist
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  options:
    - name:
  helperText:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Select input
  options:
    - name: Option 1
    - name: Option 2
    - name: Option 3
    - name: Option 4

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  helperText:
    comment: Helpful text for the user such as 'Option 1 is only available on weekends'
  id:
    instance_value: UUID
    hidden: true