# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Upcoming Happening"
  description: Shows the very next upcoming happening (only shows one).
  icon:
  tags: [happenings, connected]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  contents:
    sectionId:
    showNote: true
    showCancelled: true
    tags:
    showCountdown: false
    noHappeningsHeading: bookshop:generic/heading
  styles:
    color_group: primary
    countDownPosition: center
    backgroundOpacity: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  color_group:
    comment: >-
      This color group is applied to the No Happenings Heading.
  tags:
    hidden: false
    type: multiselect
    label: Filter by tags
    comment: >-
      Filter by specifc tags (set up in the happenings data file) to show only those happenings. Leave blank to show all.
      Make sure the tag you want to filter on is set up in the happenings data file.
    options:
      values: data.blogTags
  noHappeningsHeading:
    label: No Happenings Heading
    comment: >-
      The heading to show when there are no happenings.
      If no heading is given, this section will be hidden when there are no happenings.
  backgroundOpacity:
    type: range
    options:
      min: 0
      max: 100
      step: 5
      default: 50
    comment: Set the opacity percentage of the background
  countDownPosition:
    hidden: true #'!showCountdown'
    type: choice
    options:
      allow_empty: false
      value_key: id
      values:
        - name: Left
          id: left
          icon: format_align_left
        - name: Right
          id: right
          icon: format_align_right
        - name: Center
          id: center
          icon: format_align_center