# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Image Grid Portfolio"
  description: Shows a portfolio of images in an offset grid
  icon:
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    images: 
      - image: bookshop:generic/image
        title: 
        description:
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: "A title to go with the image. (optional)"
    label: "Project Title"
  description:
    comment: "A description to go with the image. (optional)"
