# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Image Gallery Masonry 5"
  description: Masonry grid of images 5 images per set
  icon: space_dashboard
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    imageSets:
      - images: [bookshop:structure:media]
    buttons: [bookshop:structure:buttons]
    setLimit: 5
    patternLimit: 10
    imageClasses:
      - "" # This will always be empty and is needed for the grid to work
      - sm:row-span-1 sm:col-span-1 sm:row-start-1 sm:col-start-1
      - sm:row-span-1 sm:col-span-2 sm:row-start-1 sm:col-start-2
      - sm:row-span-2 sm:col-span-1 sm:row-start-1 sm:col-start-4
      - sm:row-span-1 sm:col-span-2 sm:row-start-2 sm:col-start-1
      - sm:row-span-1 sm:col-span-1 sm:row-start-2 sm:col-start-3 col-span-2
      - sm:row-span-2 sm:col-span-1 sm:row-start-1 sm:col-start-1
      - sm:row-span-1 sm:col-span-1 sm:row-start-1 sm:col-start-2
      - sm:row-span-1 sm:col-span-2 sm:row-start-1 sm:col-start-3
      - sm:row-span-1 sm:col-span-2 sm:row-start-2 sm:col-start-2
      - sm:row-span-1 sm:col-span-1 sm:row-start-2 sm:col-start-4 col-span-2
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  images:
    label: Media
  imageSets:
    comment: "Each image set can have up to 5 images. Any image added past the fifth will not show up"
  imageClasses:
    hidden: true
  setLimit:
    hidden: true
  patternLimit:
    hidden: true
