# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "RadioButtonGroup"
  description:
  icon: radio_button_unchecked
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id:
  radioButtons:
    - label:
      id:
      checked: false
      required: false
  arrangement: inline
  helperText:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: It is recommended to provide a label for this input group
  radioButtons:
    comment: It is recommended to have one option checked as a default for radio button groups
  id:
    instance_value: UUID
    hidden: true
  helperText:
    comment: Helpful text for the user such as 'Option 1 is only available on weekends'