# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Default Featured"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  happeningTitle: "something about blog"
  url: "#"
  happeningDatetime: "2020-01-01"
  cancelled: false
  blogTags: ['tag1', 'tag2']
  image: bookshop:generic/image
  summary:
  color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
