# Metadata about this component, to be used in the CMS
spec:
  structures:
    - memberCards
  label: "Default Member Card"
  description: The standard member card
  icon: person
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    name:
    titleOrDescription:
    image: bookshop:generic/image
    link:
  style:
    color_group: primary
    colorFromGroup: background

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
