# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Image Grid"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  imageSets:
    - images: [bookshop:generic/image]
  imageClasses:
  setLimit: 1
  patternLimit: 1
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  imageClasses:
    hidden: true
  setLimit:
    hidden: true
  patternLimit:
    hidden: true
