# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blog_cards
  label: "Card1"
  description: Blog post card style 1
  icon: 
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  blogTitle: "something about blog"
  url: "#"
  author: "Jane Doe"
  date: "2020-01-01"
  length: "5 min"
  blogTags: ['tag1', 'tag2']
  image: bookshop:generic/image
  color_group: primary


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  blogTitle: "something about blog"
  url: "#"
  author: "Jane Doe"
  date: "2020-01-01"
  length: "5 min"
  blogTags: ['tag1', 'tag2']
  image: bookshop:generic/image
  color_group: primary
  

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
